name: Core
version: '${project.version}'
main: com.arcunis.core.Core
api-version: '1.20'
load: STARTUP
commands:
  reload:
    permission: arcunis.core.reload

permissions:
  arcunis.core.reload:
    description: Reload things\